services:
  sftp_server:
    image: git.jisoonet.com/el/sftp_server
    container_name: sftp_server
    environment:
      SFTP_USER_PASSWORD: ${SFTP_USER_PASSWORD}
    ports:
      - "${SFTP_SERVER_PORT:-22}:22"
    volumes:
      - sftp_server:/mnt/sftp_server
    restart: unless-stopped

volumes:
  sftp_server:
    name: sftp_server

networks:
  minecraftserver:
    name: sftp_server