services:
  sftp_server:
    image: git.jisoonet.com/el/sftp_server
    container_name: sftp_server
    environment:
      - SFTP_USER_PASSWORD=${SFTP_USER_PASSWORD}
    ports:
      - "2222:22"
    restart: unless-stopped