services:
  sftp_server:
    image: git.jisoonet.com/el/sftp_server
    name: ${SFTP_SERVER_SERVICE:-sftp_server}
    environment:
      SFTP_USER_PASSWORD: ${SFTP_USER_PASSWORD}
    ports:
      - "${SFTP_SERVER_PORT:-22}:22"
    volumes:
      - sftp_server:/mnt/sftp_server
    networks:
      - sftp_server
    restart: on-failure:5

volumes:
  sftp_server:
    name: ${SFTP_SERVER_VOLUME:-sftp_server}

networks:
  sftp_server:
    name: ${SFTP_SERVER_NETWORKS:-sftp_server}